Sobre o problema reportado #$problemID$:<br>
<br>
<table border='0'>
	<tr>
		<th align='right'>Tipo:</th><td style=' border: 1px dashed #BBBBBB; padding: 5px;'>$type$</td>
		<th align='right'>Enviado por:</th><td style=' border: 1px dashed #BBBBBB; padding: 5px;'>$submitter$</td>
	</tr>
	<tr>
		<th align='right'>$categoryOrRule$:</th><td style=' border: 1px dashed #BBBBBB; padding: 5px;'>$valueCategoryOrRule$</td>
		<th align='right'>$errorTypeOrReplaceBy$:</th><td style=' border: 1px dashed #BBBBBB; padding: 5px;'>$valueErrorTypeOrReplaceBy$</td>
	</tr>
</table>
<br>
<b>Texto:</b><br>
<br>
<div style=' border: 1px dashed #BBBBBB; padding: 5px; width: 75%;'>$text$</div><br>
<br>
Veja mais em <a href='$root$errorEntry/$problemID$'>$root$errorEntry/$problemID$</a><br>